# Generated by Django 3.0.8 on 2020-07-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendsoffriends',
            name='request_receive',
        ),
        migrations.RemoveField(
            model_name='friendsoffriends',
            name='request_sent',
        ),
    ]
